//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismMahAppsSample.ModuleA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrismMahAppsSample.ModuleA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块A.
        /// </summary>
        internal static string ModuleATiles {
            get {
                return ResourceManager.GetString("ModuleATiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块A：对话框.
        /// </summary>
        internal static string Tile1ShowPopupDescription {
            get {
                return ResourceManager.GetString("Tile1ShowPopupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块APopup.
        /// </summary>
        internal static string Tile1ShowPopupTitle {
            get {
                return ResourceManager.GetString("Tile1ShowPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块A Metra消息窗口.
        /// </summary>
        internal static string Tile2ShowPopupDescription {
            get {
                return ResourceManager.GetString("Tile2ShowPopupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块A 显示消息.
        /// </summary>
        internal static string Tile2ShowPopupTitle {
            get {
                return ResourceManager.GetString("Tile2ShowPopupTitle", resourceCulture);
            }
        }
    }
}
